version: '3.9'
services:
  db:
    container_name: pg_db
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
    ports:
      - '5432:5432'
  node:
    container_name: node
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/app